<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">

  <!-- ==================== PROPERTIES ==================== -->
  
  <!-- Chassis Properties -->
  <xacro:property name="chassis_length" value="0.30"/>
  <xacro:property name="chassis_width" value="0.30"/>
  <xacro:property name="chassis_height" value="0.15"/>
  <xacro:property name="chassis_mass" value="5.0"/>
  
  <!-- Wheel Properties -->
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_mass" value="0.5"/>
  <xacro:property name="wheel_separation" value="0.32"/>
  <xacro:property name="wheel_offset_x" value="-0.05"/>
  <xacro:property name="wheel_offset_z" value="-0.05"/>
  
  <!-- Caster Wheel Properties -->
  <xacro:property name="caster_radius" value="0.025"/>
  <xacro:property name="caster_mass" value="0.1"/>
  <xacro:property name="caster_offset_x" value="0.10"/>
  <xacro:property name="caster_offset_z" value="-0.075"/>
  
  <!-- LiDAR Properties -->
  <xacro:property name="lidar_radius" value="0.05"/>
  <xacro:property name="lidar_height" value="0.04"/>
  <xacro:property name="lidar_mass" value="0.2"/>
  <xacro:property name="lidar_offset_z" value="0.095"/>
  
  <!-- ==================== COLORS ==================== -->
  
  <material name="blue">
    <color rgba="0.2 0.2 0.8 1.0"/>
  </material>
  
  <material name="black">
    <color rgba="0.1 0.1 0.1 1.0"/>
  </material>
  
  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>
  
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>
  
  <material name="green">
    <color rgba="0.0 0.8 0.0 1.0"/>
  </material>
  
  <!-- ==================== INERTIA MACROS ==================== -->
  
  <!-- Box Inertia Macro -->
  <xacro:macro name="box_inertia" params="m l w h">
    <inertia
      ixx="${(m/12.0) * (h*h + l*l)}"
      ixy="0.0"
      ixz="0.0"
      iyy="${(m/12.0) * (w*w + l*l)}"
      iyz="0.0"
      izz="${(m/12.0) * (w*w + h*h)}"/>
  </xacro:macro>
  
  <!-- Cylinder Inertia Macro -->
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia
      ixx="${(m/12.0) * (3*r*r + h*h)}"
      ixy="0.0"
      ixz="0.0"
      iyy="${(m/12.0) * (3*r*r + h*h)}"
      iyz="0.0"
      izz="${(m/2.0) * r*r}"/>
  </xacro:macro>
  
  <!-- Sphere Inertia Macro -->
  <xacro:macro name="sphere_inertia" params="m r">
    <inertia
      ixx="${(2.0/5.0) * m * r * r}"
      ixy="0.0"
      ixz="0.0"
      iyy="${(2.0/5.0) * m * r * r}"
      iyz="0.0"
      izz="${(2.0/5.0) * m * r * r}"/>
  </xacro:macro>
  
  <!-- ==================== BASE FOOTPRINT ==================== -->
  
  <link name="base_footprint"/>
  
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 ${wheel_radius - wheel_offset_z}" rpy="0 0 0"/>
  </joint>
  
  <!-- ==================== CHASSIS (BASE LINK) ==================== -->
  
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <mass value="${chassis_mass}"/>
      <xacro:box_inertia m="${chassis_mass}" l="${chassis_length}" w="${chassis_width}" h="${chassis_height}"/>
    </inertial>
  </link>
  
  <!-- Gazebo Chassis Color -->
  <gazebo reference="base_link">
    <material>Gazebo/Blue</material>
  </gazebo>
  
  <!-- ==================== WHEEL MACRO ==================== -->
  
  <xacro:macro name="drive_wheel" params="prefix y_reflect">
    
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      
      <inertial>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
      </inertial>
    </link>
    
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${wheel_offset_x} ${y_reflect * wheel_separation / 2} ${wheel_offset_z}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.1" friction="0.1"/>
    </joint>
    
    <!-- Gazebo Wheel Settings -->
    <gazebo reference="${prefix}_wheel">
      <material>Gazebo/Black</material>
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      <minDepth>0.001</minDepth>
    </gazebo>
    
  </xacro:macro>
  
  <!-- Create Left and Right Wheels -->
  <xacro:drive_wheel prefix="left" y_reflect="1"/>
  <xacro:drive_wheel prefix="right" y_reflect="-1"/>
  
  <!-- ==================== CASTER WHEEL ==================== -->
  
  <link name="caster_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${caster_mass}"/>
      <xacro:sphere_inertia m="${caster_mass}" r="${caster_radius}"/>
    </inertial>
  </link>
  
  <joint name="caster_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="${caster_offset_x} 0 ${caster_offset_z}" rpy="0 0 0"/>
  </joint>
  
  <!-- Gazebo Caster Settings (Frictionless) -->
  <gazebo reference="caster_wheel">
    <material>Gazebo/White</material>
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
  </gazebo>
  
  <!-- ==================== LIDAR ==================== -->
  
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
      <material name="red"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${lidar_mass}"/>
      <xacro:cylinder_inertia m="${lidar_mass}" r="${lidar_radius}" h="${lidar_height}"/>
    </inertial>
  </link>
  
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${chassis_height + lidar_offset_z}" rpy="0 0 0"/>
  </joint>
  
  <!-- Gazebo LiDAR Color -->
  <gazebo reference="lidar_link">
    <material>Gazebo/Red</material>
  </gazebo>
  
   <!-- ==================== IGNITION GAZEBO PLUGINS ==================== -->
  
  <!-- Differential Drive Plugin -->
  <gazebo>
    <plugin filename="ignition-gazebo-diff-drive-system" 
            name="ignition::gazebo::systems::DiffDrive">
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>0.32</wheel_separation>
      <wheel_radius>0.05</wheel_radius>
      <odom_publish_frequency>50</odom_publish_frequency>
      <max_linear_acceleration>1.0</max_linear_acceleration>
      <min_linear_acceleration>-1.0</min_linear_acceleration>
      <max_angular_acceleration>2.0</max_angular_acceleration>
      <min_angular_acceleration>-2.0</min_angular_acceleration>
      <max_linear_velocity>0.5</max_linear_velocity>
      <min_linear_velocity>-0.5</min_linear_velocity>
      <max_angular_velocity>1.0</max_angular_velocity>
      <min_angular_velocity>-1.0</min_angular_velocity>
      <topic>cmd_vel</topic>
      <odom_topic>odom</odom_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>base_footprint</child_frame_id>
      <tf_topic>/tf</tf_topic>
    </plugin>
  </gazebo>
  
  <!-- Joint State Publisher Plugin -->
  <gazebo>
    <plugin filename="ignition-gazebo-joint-state-publisher-system" 
            name="ignition::gazebo::systems::JointStatePublisher">
      <joint_name>left_wheel_joint</joint_name>
      <joint_name>right_wheel_joint</joint_name>
      <update_rate>50</update_rate>
      <topic>joint_states</topic>
    </plugin>
  </gazebo>
  
  <!-- LiDAR Sensor -->
  <gazebo reference="lidar_link">
    <sensor name="lidar_sensor" type="gpu_lidar">
      <pose>0 0 0 0 0 0</pose>
      <topic>scan</topic>
      <update_rate>10</update_rate>
      <lidar>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
          <vertical>
            <samples>1</samples>
            <resolution>1</resolution>
            <min_angle>0</min_angle>
            <max_angle>0</max_angle>
          </vertical>
        </scan>
        <range>
          <min>0.1</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </lidar>
      <visualize>true</visualize>
      <always_on>true</always_on>
    </sensor>
  </gazebo>
</robot>